version: "3.9"
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "test_web_db"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
       - ./db_data:/var/lib/postgresql/data
    ports:
      - 1101:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d test_web_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
volumes:
  db_data: